spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none #주의 사용에 따라 create, update 사용 후 none으로 변경해주세요
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
#        show_sql: true   # 하이버네이트 기본 SQL 출력 옵션
#        format_sql: true # 하이버네이트 기본 SQL 포맷팅 옵션

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 1800000

gpt:
  key: ${GPT_API_KEY}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ, Asia/Seoul} [%X{request_id}] %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
  file:
    name: logs/spring-boot-app.log